### ISSUE TITLE
app.py broken due to module issue

### ISSUE THREAD

**Issue by sandrich** [sandrich/classifying_digits_mnist#9]
Seems that one of my changes broke the app

```
$ python src/app.py -h
Traceback (most recent call last):
  File "src/app.py", line 1, in <module>
    from src import dataset
ModuleNotFoundError: No module named 'src'

```

**Comment by bigskapinsky** [comment]
oh man this is the kind of thing I wasn't sure about the structure. I don't know exactly what the cleanest way to import .py files as modules is...

**Comment by sandrich** [comment]
Maybe we should look into this? https://docs.python-guide.org/writing/structure/

**Comment by bigskapinsky** [comment]
fixed with refactoring branch, just approve the merge and it's done
